### ISSUE TITLE
Richner&Singh 3 by LM

### ISSUE THREAD

**Issue by kausal-flow** [kausalflow/colorteller#17]
2021-11-30T20:31:34.805Z

- Name: Richner&Singh 3
- Author: LM
- HEX: #4770B3,#CAD93F,#65338D
- Summary:From "[Using Colors For Data Visualization With Large Categories. In: Intelligaia [Internet]. [cited 30 Nov 2021]](https://intelligaia.com/using-colors-for-data-visualization-with-large-categories.php)"

Please check the PRs.

**Comment by emptymalei** [comment]
#20
