### ISSUE TITLE
Richner&Singh 3 by LM

### ISSUE THREAD

**Issue by kausal-flow** [kausalflow/colorteller#18]
2021-11-30T20:33:06.611Z

- Name: Richner&Singh 6
- Author: LM
- HEX: #4770B3,#26727B,#E4B031,#50AED3,#CAD93F,#9E9EA2
- Summary:From "[Using Colors For Data Visualization With Large Categories. In: Intelligaia [Internet]. [cited 30 Nov 2021]](https://intelligaia.com/using-colors-for-data-visualization-with-large-categories.php)"

Please check the PRs.

**Comment by emptymalei** [comment]
#19
