### ISSUE TITLE
awtools primary one by LM

### ISSUE THREAD

**Issue by kausal-flow** [kausalflow/colorteller#21]
2021-12-01T20:46:47.105Z

- Name: awtools primary one
- Author: LM
- HEX: #F7DC05,#3d98d3,#EC0B88,#5e35b1,#f9791e,#3dd378,#c6c6c6,#444444
- Summary:primary color from [awtools](https://github.com/awhstin/awtools/blob/2bf741d2393ce122f9dca09eb40066948efb6f95/R/colors.R#L4)

Please check the PRs.

**Comment by emptymalei** [comment]
#22
